ラビット☆チャレンジ 提出レポート

# 機械学習

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#機械学習" data-toc-modified-id="機械学習-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>機械学習</a></span><ul class="toc-item"><li><span><a href="#参考" data-toc-modified-id="参考-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>参考</a></span></li><li><span><a href="#module-import" data-toc-modified-id="module-import-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>module import</a></span></li><li><span><a href="#線形回帰モデル" data-toc-modified-id="線形回帰モデル-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>線形回帰モデル</a></span><ul class="toc-item"><li><span><a href="#要点まとめ" data-toc-modified-id="要点まとめ-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>要点まとめ</a></span></li><li><span><a href="#データ分割・学習" data-toc-modified-id="データ分割・学習-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>データ分割・学習</a></span></li><li><span><a href="#ハンズオン（住宅価格予測）" data-toc-modified-id="ハンズオン（住宅価格予測）-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>ハンズオン（住宅価格予測）</a></span><ul class="toc-item"><li><span><a href="#データの確認" data-toc-modified-id="データの確認-1.3.3.1"><span class="toc-item-num">1.3.3.1&nbsp;&nbsp;</span>データの確認</a></span></li><li><span><a href="#線形単回帰分析" data-toc-modified-id="線形単回帰分析-1.3.3.2"><span class="toc-item-num">1.3.3.2&nbsp;&nbsp;</span>線形単回帰分析</a></span></li><li><span><a href="#重回帰分析(2変数)" data-toc-modified-id="重回帰分析(2変数)-1.3.3.3"><span class="toc-item-num">1.3.3.3&nbsp;&nbsp;</span>重回帰分析(2変数)</a></span></li><li><span><a href="#回帰係数と切片の値を確認" data-toc-modified-id="回帰係数と切片の値を確認-1.3.3.4"><span class="toc-item-num">1.3.3.4&nbsp;&nbsp;</span>回帰係数と切片の値を確認</a></span></li></ul></li></ul></li><li><span><a href="#非線形回帰モデル" data-toc-modified-id="非線形回帰モデル-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>非線形回帰モデル</a></span><ul class="toc-item"><li><span><a href="#非線形回帰モデル" data-toc-modified-id="非線形回帰モデル-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>非線形回帰モデル</a></span></li><li><span><a href="#正則化法" data-toc-modified-id="正則化法-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>正則化法</a></span></li><li><span><a href="#モデル選択" data-toc-modified-id="モデル選択-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>モデル選択</a></span></li></ul></li><li><span><a href="#ロジスティック回帰" data-toc-modified-id="ロジスティック回帰-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>ロジスティック回帰</a></span><ul class="toc-item"><li><span><a href="#ロジスティック回帰" data-toc-modified-id="ロジスティック回帰-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>ロジスティック回帰</a></span></li><li><span><a href="#最尤推定" data-toc-modified-id="最尤推定-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>最尤推定</a></span></li><li><span><a href="#勾配降下法" data-toc-modified-id="勾配降下法-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>勾配降下法</a></span></li><li><span><a href="#モデル評価" data-toc-modified-id="モデル評価-1.5.4"><span class="toc-item-num">1.5.4&nbsp;&nbsp;</span>モデル評価</a></span></li></ul></li></ul></li></ul></div>

## 参考

- 評価関数について  
    - [機械学習で使われる評価関数まとめ - Qiita](https://qiita.com/monda00/items/a2ee8e0da51953c24da8)
- 自分の勉強記録・ノート  
    - 線形回帰  
        - [DIC Sprint 機械学習スクラッチ　線形回帰](https://github.com/SatoRiyu/diveintocode-ml/blob/master/Sprint/Sprint3.ipynb)
    - ロジスティック回帰  
        - [DIC Sprint 機械学習スクラッチ ロジスティック回帰](https://github.com/SatoRiyu/diveintocode-ml/blob/master/Sprint/Sprint4.ipynb)

## module import

In [1]:
#from モジュール名 import クラス名（もしくは関数名や変数名）

from sklearn.datasets import load_boston
from pandas import DataFrame
import numpy as np

## sklearnモジュールからLinearRegressionをインポート
from sklearn.linear_model import LinearRegression

## 線形回帰モデル

### 要点まとめ

- 入力 
    - 説明変数(特徴量)   
       １次元以上のベクトル(vector)  
      $$
       \boldsymbol{x} = (x_{1}, x_{2}, ..., x_{m})^{\mathrm{T}} \in \mathbb{R}^{m}
      $$
- 出力
    - 目的変数  
      1次元(scalar)
      $$
       y \in \mathbb{R}^{1}
      $$
- パラメータ  
    - 各特徴量に対する重み $\boldsymbol{w}=  (w_{1}, w_{2}, ..., w_{m})$
    - 切片(bias) $w_{0}$
- 処理  
    - 式  
      $$
      \hat{y} = \boldsymbol{w}^{\mathrm{T}} \cdot{\boldsymbol{x}} + w_0 = \sum_{j=1}^{m}w_{j}x_{j} + w_{0}
      $$
    - 線形結合
        - 入力とパラメータの内積  
            - 自分の言葉で言い換えると「特徴量と重みのドット積」  
    - 切片($w_{0}$)を足し合わせる  
        - X軸に対して平行移動する  
- 評価関数  
    - MSE  
        - 日本語では「平均二乗誤差」、「残差平方和」  
        [機械学習で使われる評価関数まとめ - Qiita](https://qiita.com/monda00/items/a2ee8e0da51953c24da8)
- 目的関数（損失関数）  
    - 最小二乗法  
    - 最尤法  
- ハイパーパラメータ
    - 学習率  

### データ分割・学習

- データの分割  
    - 目的 モデルの汎化性能(Generalization)を測るため
        - 既知のデータに対してどれだけ精度高く目的変数の値を出力出来ても意味がない。辞書やデータベースを用意すれば済んでしまう。それがエキスパートシステムか？
    - 分割方法　　
        - k-fold法
- 学習  
    - 学習データで学習、検証用データで評価検証
    - 評価関数の値を目的関数に渡す。最小化、あるいは最大化する。

### ハンズオン（住宅価格予測）

#### データの確認

In [2]:
# ボストンデータを"boston"というインスタンスにインポート
boston = load_boston()

In [3]:
#インポートしたデータを確認(data / target / feature_names / DESCR)
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [4]:
#DESCR変数の中身を確認
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
#feature_names変数の中身を確認
#カラム名
print(boston['feature_names'])

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [6]:
#data変数(説明変数)の中身を確認
print(boston['data'])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [7]:
#target変数(目的変数)の中身を確認
print(boston['target'])

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [8]:
#　説明変数らをDataFrameへ変換
df = DataFrame(data=boston.data, columns = boston.feature_names)

In [9]:
# 目的変数をDataFrameへ追加
df['PRICE'] = np.array(boston.target)

In [10]:
# 最初の5行を表示
df.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

#### 線形単回帰分析

In [11]:
# 説明変数
data = df.loc[:, ['RM']].values

In [12]:
# 目的変数
target = df.loc[:, 'PRICE'].values

In [13]:
# オブジェクト生成
model = LinearRegression()
#model.get_params()
#model = LinearRegression(fit_intercept = True, normalize = False, copy_X = True,  n_jobs = 1)

In [14]:
# fit関数でパラメータ推定
model.fit(data, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
#予測
model.predict([[1]])

array([-25.5685118])

#### 重回帰分析(2変数)

In [16]:
#カラムを指定してデータを表示
df[['CRIM', 'RM']].head()

CRIM     RM
0  0.00632  6.575
1  0.02731  6.421
2  0.02729  7.185
3  0.03237  6.998
4  0.06905  7.147

In [17]:
# 説明変数
data2 = df.loc[:, ['CRIM', 'RM']].values
# 目的変数
target2 = df.loc[:, 'PRICE'].values

In [18]:
# オブジェクト生成
model2 = LinearRegression()

In [19]:
# fit関数でパラメータ推定
model2.fit(data2, target2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
model2.predict([[0.2, 7]])

array([29.43977562])

#### 回帰係数と切片の値を確認

In [21]:
# 単回帰の回帰係数と切片を出力
print('推定された回帰係数: %.3f, 推定された切片 : %.3f' % (model.coef_, model.intercept_))

推定された回帰係数: 9.102, 推定された切片 : -34.671


In [22]:
# 重回帰の回帰係数と切片を出力
print(model.coef_)
print(model.intercept_)

[9.10210898]
-34.67062077643857


## 非線形回帰モデル

### 非線形回帰モデル

- 基底展開法  
    - 回帰関数  
      $$
       y_{i} = f(x_{i}) + \varepsilon_{i}
      $$
      $$
       y_{i} = w_{0} + \sum_{j=1}^{m}w_{j}\phi_{j}(x_{i}) + \varepsilon_{i}
      $$
        - 切片 $w_{0}$  
        - 基底関数 $\phi_{j}(x_{i})$  
          既知の非線形関数、**線形の写像によって非線形化する**らしい  
          計画行列  
          - よく使われる基底関数
              - 多項式関数
              - ガウス型基底関数  
                 バンド幅$h_{j}$  
              $$
              \phi_{j}(x_{i}) = \exp(\frac{(x-\mu_{j})^{2}}{2h_{j}})
              $$
              - スプライン関数 / Bスプライン関数
        - パラメータベクトル $\varepsilon_{i}$ 

### 正則化法

- 未学習(underfitting)  
    - 学習データに対して誤差が小さくならない  
        - モデルの表現力が低いため、表現力の高いモデルを利用する
- 過学習(overfitting)  
    - 学習データに対する誤差は小さいが、汎化性能が低い  
        - 学習データを増やす  
        - 不要な基底関数(変数)を削除して表現力を抑止  
        - 正則化法(正則化項を加える)を利用して表現力を抑止  

- 正則化法(罰則化法)  
$$
S_{\gamma} = (y-\phi w)^{T}(y - \phi w)+\gamma R(w) \; \; \gamma(>0)
$$
    - 「モデルの複雑さに伴って、その値が大きくなる正則化項(罰則化項)を課した関数」を最小化
    - 正則化項(罰則化項)  
        - 形状によって種類がある  
            - 正則化項無し : 最小二乗推定量
            - L2ノルムを利用 : Ridge推定量
              - 縮小推定  
                パラメータを0に近づけるように推定
            - L1ノルムを利用 : Lasso推定量
                - スパース推定  
                  いくつかのパラメータを正確に0に推定  
                  - 次元削減  
                    不要な基底関数、特徴量を排除することができる！学習コストの軽減に繋がる！
    - 正則化(平滑化)パラメータ $\gamma$  
        - モデルの曲線の滑らかさを調整  
            - 適切に決める必要あり  
              パラメータを小さくすると、制約面が大きくなる  
              パラメータを大きくすると、制約面が小さくなる  

### モデル選択

- ホールドアウト法  
    - 学習用データと検証データを固定する  
    - 学習用データが減ってしまう
    - データに外れ値の偏り等が生じてしまう場合があり、学習がうまくいかないことがある
- クロスバリデーション法  
    - データをk分割して、(k-1)個のデータで学習、１個のデータで検証する。
    - 学習、検証するデータをずらしていく

## ロジスティック回帰

### ロジスティック回帰

- 入力 
    - 説明変数(特徴量)   
       m次元のベクトル(vector)  
      $$
       \boldsymbol{x} = (x_{1}, x_{2}, ..., x_{m})^{\mathrm{T}} \in \mathbb{R}^{m}
      $$
- 出力
    - 目的変数  
      1次元(scalar)
      $$
       y \in \{ 0,1 \}
      $$
- パラメータ  
    - 各特徴量に対する重み $\boldsymbol{w}=  (w_{1}, w_{2}, ..., w_{m})$
    - 切片(bias) $w_{0}$
- 処理  
  途中までは線形回帰モデルと同じ。下記の式の$\hat{y}$をシグモイド関数の引数とし、その返値がクラスに分類される確率になる。  
  各クラスに対して、分類される確率を求めて、最も確率の高いクラスに分類する。  
    - 式  
      $$
      \hat{y} = \boldsymbol{w}^{\mathrm{T}} \cdot{\boldsymbol{x}} + w_0 = \sum_{j=1}^{m}w_{j}x_{j} + w_{0}
      $$
    - 線形結合
        - 入力とパラメータの内積  
            - 自分の言葉で言い換えると「特徴量と重みのドット積」  
    - 切片($w_{0}$)を足し合わせる  
        - X軸に対して平行移動する  
    - シグモイド関数  
     $$
     \sigma (x) = \frac{1}{1+\exp{-ax} }
     $$
         - 入力は実数、出力は0--1  
         - そのクラスに分類される確率を表現  
         - 単調増加関数  
         - $a$を増加させると、x=0付近での曲線の勾配が増加  
         - $a$を極めて大きくすると単調ステップ関数に近似する  
         - バイアス変化は段差の位置  
         - 性質  
             - **シグモイド関数の微分は、シグモイド関数自身で表現することが可能**
             - 尤度関数の微分を行う際に利用する
- 評価関数  
    - MSE  
        - 日本語では「平均二乗誤差」、「残差平方和」  
        [機械学習で使われる評価関数まとめ - Qiita](https://qiita.com/monda00/items/a2ee8e0da51953c24da8)
- 目的関数（損失関数）  
    - 最小二乗法  
    - 最尤法  
- ハイパーパラメータ
    - 学習率  
- 確率分布
    - ベルヌーイ分布

### 最尤推定

- 尤度  
  仮定する確率分布のパラメータのもっともらしさの度合い。ここでいうパラメータは、ベルヌーイ分布でいうp（発生確率、成功確率）である。
- 最尤推定は尤度からパラメータを推定する。
    - 尤度関数を最大化する
        - 同時確率の計算  
        - そのままの値ではなく、対数を最大化する
            - 対数尤度関数  
              計算が簡単になる
        - ***尤度関数にマイナスを掛けた値を最小化し、最小二乗法の最小化と合わせる！！！***  
          知らなかった！

### 勾配降下法

- 最尤法の大域的最適解をピンポイントで求められない。
    - 局所解を求める。
- 勾配降下法  
    - パラメータを更新するのに全てのデータに対して計算をする必要がある
    - データサイズによってはメモリに載り切らない問題が発生する
        - ここで確率的勾配降下法を利用する
- 確率的勾配降下法(SGD)  
    - ランダムにデータ１個を選んで逐次パラメータを更新する  


### モデル評価